name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code that reproduces the issue.
      render: swift
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: swift-nostr-client version
      placeholder: e.g., 0.1.0
    validations:
      required: true
