name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like? Why?
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Example
      description: How would this feature be used?
      render: swift
    validations:
      required: false
