import Foundation
import NostrClient

/// A parsed NIP-47 `nostr+walletconnect://` connection string.
///
/// The wallet service issues this URI to authorize a client. It carries everything the client needs
/// to talk to the wallet:
///
/// ```text
/// nostr+walletconnect://<wallet-pubkey-hex>?relay=<wss url>&secret=<32-byte hex>&lud16=<address>
/// ```
///
/// - The host is the wallet service's public key (hex).
/// - `relay` is the relay the wallet listens on; it may appear more than once.
/// - `secret` is a 32-byte private key generated by the wallet for **this client**. The client
///   signs its request events and encrypts their payloads with it, so the user's main Nostr key is
///   never exposed (see ``clientKeyPair()``).
/// - `lud16` is an optional lightning address the client can use to set up payments.
///
/// https://github.com/nostr-protocol/nips/blob/master/47.md
public struct WalletConnectURI: Sendable, Hashable {
    /// The wallet service's public key (32-byte hex).
    public let walletPubkey: String

    /// The relays the wallet service listens on. Always at least one.
    public let relays: [URL]

    /// The 32-byte client secret key. The client signs and encrypts with this key.
    public let secret: Data

    /// An optional lightning address (lud16) the wallet advertised.
    public let lud16: String?

    /// The URI scheme, without the `://` separator.
    public static let scheme = "nostr+walletconnect"

    /// Creates a connection from its components, validating the wallet pubkey and secret.
    ///
    /// - Parameters:
    ///   - walletPubkey: The wallet service's public key (must be 32-byte hex).
    ///   - relays: The relays the wallet listens on (must contain at least one).
    ///   - secret: The 32-byte client secret key (must be a valid secp256k1 private key).
    ///   - lud16: An optional lightning address.
    /// - Throws: ``WalletConnectError/invalidURI(reason:)`` if any field fails validation.
    public init(walletPubkey: String, relays: [URL], secret: Data, lud16: String? = nil) throws {
        let normalizedPubkey = walletPubkey.lowercased()
        guard NWCHex.isValid(normalizedPubkey, byteCount: 32) else {
            throw WalletConnectError.invalidURI(reason: "wallet pubkey must be 32-byte hex")
        }
        guard !relays.isEmpty else {
            throw WalletConnectError.invalidURI(reason: "at least one relay is required")
        }
        guard secret.count == 32 else {
            throw WalletConnectError.invalidURI(reason: "secret must be 32 bytes")
        }
        // Reject a secret that is not a usable secp256k1 private key now, rather than at first use.
        guard (try? KeyPair(privateKey: secret)) != nil else {
            throw WalletConnectError.invalidURI(reason: "secret is not a valid private key")
        }

        self.walletPubkey = normalizedPubkey
        self.relays = relays
        self.secret = secret
        self.lud16 = lud16
    }

    /// Parses a `nostr+walletconnect://` connection string.
    ///
    /// - Parameter string: The connection string issued by the wallet service.
    /// - Throws: ``WalletConnectError/invalidURI(reason:)`` if the string is malformed or missing
    ///   required fields.
    public init(string: String) throws {
        guard let components = URLComponents(string: string),
            components.scheme?.lowercased() == Self.scheme
        else {
            throw WalletConnectError.invalidURI(reason: "scheme must be \(Self.scheme)://")
        }

        guard let host = components.host, !host.isEmpty else {
            throw WalletConnectError.invalidURI(reason: "missing wallet pubkey")
        }

        let queryItems = components.queryItems ?? []

        let relayValues = queryItems.filter { $0.name == "relay" }.compactMap { $0.value }
        let relays = relayValues.compactMap { URL(string: $0) }
        guard !relayValues.isEmpty, relays.count == relayValues.count else {
            throw WalletConnectError.invalidURI(reason: "missing or malformed relay")
        }

        guard let secretHex = queryItems.first(where: { $0.name == "secret" })?.value,
            let secret = NWCHex.data(from: secretHex)
        else {
            throw WalletConnectError.invalidURI(reason: "missing or malformed secret")
        }

        let lud16 = queryItems.first(where: { $0.name == "lud16" })?.value

        try self.init(walletPubkey: host, relays: relays, secret: secret, lud16: lud16)
    }

    /// The connection string, with each relay percent-encoded as a `relay` query parameter.
    public var stringValue: String {
        var components = URLComponents()
        components.scheme = Self.scheme
        components.host = walletPubkey

        var items = relays.map { URLQueryItem(name: "relay", value: $0.absoluteString) }
        items.append(URLQueryItem(name: "secret", value: NWCHex.string(from: secret)))
        if let lud16 {
            items.append(URLQueryItem(name: "lud16", value: lud16))
        }
        components.queryItems = items

        return components.string ?? ""
    }

    /// The client identity derived from ``secret`` — used to sign requests and encrypt payloads.
    public func clientKeyPair() throws -> KeyPair {
        try KeyPair(privateKey: secret)
    }

    /// A signer for the client identity. Convenience over ``clientKeyPair()``.
    public func clientSigner() throws -> EventSigner {
        EventSigner(keyPair: try clientKeyPair())
    }

    /// The client's public key (hex), derived from ``secret``.
    public var clientPublicKeyHex: String {
        get throws {
            try clientKeyPair().publicKeyHex
        }
    }
}
